apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cvmfs.fullname" . }}-cfgmap-default-local
  labels:
    {{- include "cvmfs.labels" . | nindent 4 }}
data:
  default.local: |
    {{- range $key,$val := .Values.default_local }}
    {{ $key }}='{{ $val }}'
    {{- end }}
    CVMFS_REPOSITORIES='{{ template "repolist_csv" . }}'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cvmfs.fullname" . }}-cfgmap-config-d
  labels:
    {{- include "cvmfs.labels" . | nindent 4 }}
data:
  {{- range $repo,$custom_config := .Values.config_d }}
  {{ $repo }}.local: |
    {{- range $key,$val := $custom_config }}
    {{ $key }}='{{ $val }}'
    {{- end }}
  {{- end }}

