FROM 	    gitlab-registry.cern.ch/linuxsupport/alma9-base

RUN         dnf -y update
RUN         dnf -y install filesystem
RUN         dnf -y install dnf-utils && dnf config-manager --set-enabled crb
RUN         dnf -y install epel-release
RUN         dnf -y install                     \
                       clang-analyzer          \
                       clang-tools-extra       \
                       cmake                   \
                       curl-devel              \
                       fuse-devel              \
                       fuse3-devel             \
                       gcc-c++                 \
                       gdb                     \
                       git                     \
                       golang                  \
                       hardlink                \
                       libattr-devel           \
                       libcap-devel            \
                       libffi-devel            \
                       libuuid-devel           \
                       make                    \
                       openssl-devel           \
                       python3-devel           \
                       rpm-build               \
                       ruby-devel              \
                       selinux-policy-devel    \
                       selinux-policy-targeted \
                       systemd                 \
                       which                   \
                       valgrind-devel          \
                       voms-devel              \
                       zlib-devel              \
                       attr                    \
                       autofs                  \
                       fuse                    \
                       httpd

RUN GOBIN=/usr/bin go install github.com/jstemmer/go-junit-report@latest

RUN git clone https://github.com/cvmfs/cvmfs && \
    cd cvmfs && mkdir build && cd build && \
    cmake -S .. && make -j && make install

CMD ["/usr/sbin/init"]

